### ISSUE TITLE
"use live input" failes

### ISSUE THREAD

**Issue by batchku** [zrispo/dranimate-browser#10]
steps to repeat:
1.  click on "use demo puppet"
2.  click on "use live input"

![image](https://cloud.githubusercontent.com/assets/518356/16902306/94c3be7c-4c29-11e6-9746-9f8a0c525a1c.png)

**Comment by zachrispoli** [comment]
Weird thing: Mic input thru browser only works on HTTPS.

You can host your own HTTPS server though lmk if u want me to show u
