### ISSUE TITLE
Three.js unable to invert matrix, whatever that means.

### ISSUE THREAD

**Issue by paul1peng** [zrispo/dranimate-browser#17]
Upon loading a puppet into the UI'd version of dranimate, this thing keeps getting printed out, a lot.

<img width="230" alt="screen shot 2016-08-05 at 6 38 52 pm" src="https://cloud.githubusercontent.com/assets/6415190/17452179/e4897e72-5b3a-11e6-8527-6da178fb48f7.png">

**Comment by zachrispoli** [comment]
This has to do with the bounding boxes

**Comment by zachrispoli** [comment]
FIX'D IT
